# Generated by Django 4.0.1 on 2022-02-05 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='static/profile/user-default.jpg', null=True, upload_to='static/profile/')),
                ('name', models.CharField(max_length=255)),
                ('tin', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('ytt', 'YaTT'), ('yuridik', 'Yuridik shaxs'), ('jismoniy', 'Jismoniy shaxs'), ('tanirovka', 'Tanirovka'), ('auction', 'Auksion'), ('teacher', "O'qituvchi")], max_length=255)),
                ('gov_login', models.CharField(blank=True, max_length=255, null=True)),
                ('gov_password', models.CharField(blank=True, max_length=255, null=True)),
                ('jshshir', models.CharField(blank=True, max_length=255, null=True)),
                ('guvohnoma_file', models.FileField(blank=True, default='static/guvohnoma/guvohnoma.jpg', null=True, upload_to='static/guvohnoma/')),
                ('guvohnoma_exp', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('director_tin', models.CharField(blank=True, max_length=255, null=True)),
                ('phone1', models.CharField(blank=True, max_length=255, null=True)),
                ('phone2', models.CharField(blank=True, max_length=255, null=True)),
                ('phone3', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.FileField(blank=True, null=True, upload_to='static/keys')),
                ('key_exp', models.DateField(blank=True, null=True)),
                ('passport', models.ImageField(blank=True, default='static/passport/passport-default.jpg', null=True, upload_to='static/passport/')),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('tex_number', models.CharField(blank=True, max_length=255, null=True)),
                ('text_series', models.CharField(blank=True, max_length=255, null=True)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('ustav', models.ImageField(blank=True, default='static/ustav/ustav-default.jpg', null=True, upload_to='static/ustav/')),
                ('selfy', models.ImageField(blank=True, default='static/selfy/selfy-default.jpg', null=True, upload_to='static/selfy/')),
                ('order1', models.CharField(blank=True, max_length=255, null=True)),
                ('order2', models.CharField(blank=True, max_length=255, null=True)),
                ('order3', models.CharField(blank=True, max_length=255, null=True)),
                ('auc_login', models.CharField(blank=True, max_length=255, null=True)),
                ('auc_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, default='static/profile/user-default.jpg', null=True, upload_to='')),
                ('status', models.CharField(choices=[('user', 'Oddiy foydalanuvchi'), ('superuser', 'Nazoratchi'), ('admin', 'Admin')], max_length=200)),
                ('office', models.CharField(choices=[('1', 'XXI ASR BUXGALTERIYA'), ('2', 'XXI ASR KOMPYUTER XIZMATLARI'), ('3', 'XXI ASR BUXGALTERIYA XIZMATLARI MARKAZI')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Narxlanmagan'), ('5', 'Bajarilmagan'), ('10', 'Bajarilgan')], default='0', max_length=255)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('loaded_date', models.DateTimeField(auto_now_add=True)),
                ('period', models.DateField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='static/files')),
                ('answer', models.TextField(blank=True, max_length=350, null=True)),
                ('office', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reciever', to='base.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='base.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.service')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('given_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DateField(null=True)),
                ('status', models.CharField(choices=[('0', 'Bajarilmagan'), ('5', 'Jarayonda'), ('10', 'Tugatilgan')], default='0', max_length=255)),
                ('given_file', models.FileField(blank=True, null=True, upload_to='static/files/task')),
                ('answer_text', models.TextField(blank=True, max_length=500, null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='static/files/task')),
                ('office', models.CharField(choices=[('1', 'XXI ASR BUXGALTERIYA'), ('2', 'XXI ASR KOMPYUTER XIZMATLARI'), ('3', 'XXI ASR BUXGALTERIYA XIZMATLARI MARKAZI')], max_length=200)),
                ('client', models.ManyToManyField(blank=True, null=True, to='base.Client')),
                ('user', models.ManyToManyField(to='base.Profile')),
            ],
            options={
                'ordering': ['-given_date'],
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'Raqam kiritilmagan'), ('5', 'Raqam xato kiritilgan'), ('10', 'Yuborilgan')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('period', models.DateField(max_length=255)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('payed', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.client')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(to='base.Profile')),
            ],
        ),
    ]
