# Generated by Django 4.0.1 on 2022-02-06 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-period']},
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
            preserve_default=False,
        ),
    ]
