# Generated by Django 4.0.1 on 2022-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_notes_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMStext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=300)),
            ],
        ),
    ]
