# Generated by Django 4.0.1 on 2022-02-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever', to='base.profile'),
        ),
    ]
