# Generated by Django 4.0.1 on 2022-02-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_upload_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='static/profile/user-default.jpg', null=True, upload_to='static/profile/'),
        ),
    ]
