# Generated by Django 4.0.1 on 2022-02-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-status']},
        ),
    ]
