# Generated by Django 4.0.1 on 2022-02-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_task_user_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='guvohnoma_file',
            field=models.FileField(blank=True, null=True, upload_to='static/guvohnoma/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='static/passport/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='selfy',
            field=models.ImageField(blank=True, null=True, upload_to='static/selfy/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ustav',
            field=models.ImageField(blank=True, null=True, upload_to='static/ustav/'),
        ),
    ]
