# Generated by Django 4.0.1 on 2022-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_client_passport_alter_client_selfy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ruxsatnoma',
            field=models.FileField(blank=True, null=True, upload_to='static/ruxsatnoma/'),
        ),
        migrations.AddField(
            model_name='client',
            name='texpas',
            field=models.FileField(blank=True, null=True, upload_to='static/texpas/'),
        ),
    ]
