# Generated by Django 4.0.1 on 2022-02-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_client_ruxsatnoma_client_texpas'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('aylanma', 'Aylanma'), ('oddiy', 'Oddiy')], max_length=255, null=True),
        ),
    ]
