# Generated by Django 4.0.1 on 2022-03-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_client_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='work_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
