# Generated by Django 4.0.1 on 2022-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_client_school_client_work_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
