# Generated by Django 4.0.1 on 2022-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='telegramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='static/files/telegram')),
                ('post_type', models.CharField(max_length=255)),
                ('client_type', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
